# Generated by Django 6.0.7 on 2026-07-13 23:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="date_added",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date added"
            ),
        ),
    ]
