# Generated by Django 6.0.7 on 2026-07-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0002_dish_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.CharField(
                default="123 Main Street City, State", max_length=50
            ),
        ),
    ]
