#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "$DJANGOUSER";
	CREATE DATABASE "$DJANGODB";
	GRANT ALL PRIVILEGES ON DATABASE docker TO docker;
EOSQL
