#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "$DJANGO_USER";
	CREATE DATABASE "$DJANGO_DB";
	\c "$DJANGO_DB";
	GRANT CREATE ON SCHEMA public TO "$DJANGO_USER";
	GRANT USAGE ON SCHEMA public TO "$DJANGO_USER"
EOSQL
